import {
  BanknoteArrowDown,
  ChartNoAxesCombined,
  Coins,
  Home,
  Package,
  Receipt,
  Settings,
  ShoppingBag,
  ShoppingCart,
  Users,
  Warehouse,
} from 'lucide-react';

export const menuOptions = [
  {
    id: 0,
    name: 'Inicio',
    url: '/',
    divider: false,
    icon: Home,
  },
  {
    id: 1,
    name: 'Informes',
    url: '/informes',
    divider: true,
    icon: ChartNoAxesCombined,
  },
  {
    id: 2,
    name: 'Ventas',
    url: '/ventas',
    divider: false,
    icon: Coins,
  },
  {
    id: 3,
    name: 'Inventario',
    url: '/inventario',
    divider: false,
    icon: Warehouse,
  },
  {
    id: 4,
    name: 'Productos',
    url: '/productos',
    divider: true,
    icon: Package,
  },
  {
    id: 5,
    name: 'Pedidos',
    url: '/pedidos',
    divider: false,
    icon: ShoppingBag,
  },
  {
    id: 6,
    name: 'Recibos',
    url: '/recibos',
    divider: true,
    icon: Receipt,
  },
  {
    id: 7,
    name: 'Compras',
    url: '/compras',
    divider: false,
    icon: ShoppingCart,
  },
  {
    id: 8,
    name: 'Gastos',
    url: '/gastos',
    divider: true,
    icon: BanknoteArrowDown,
  },
  {
    id: 9,
    name: 'Clientes',
    url: '/clientes',
    divider: false,
    icon: Users,
  },
  {
    id: 10,
    name: 'Ajustes',
    url: '/ajustes',
    divider: false,
    icon: Settings,
  },
];
