export const menuOptions = [
  {
    id: 0,
    name: 'Inicio',
    path: '/',
    url: '/',
    divider: false,
  },
  {
    id: 1,
    name: 'Informes',
    path: '/informes',
    url: '/informes',
    divider: true,
  },
  {
    id: 2,
    name: 'Ventas',
    path: '/ventas',
    url: '/ventas',
    divider: false,
  },
  {
    id: 3,
    name: 'Inventario',
    path: '/inventario',
    url: '/inventario',
    divider: false,
  },
  {
    id: 4,
    name: 'Productos',
    path: '/productos',
    url: '/productos',
    divider: true,
  },
  {
    id: 5,
    name: 'Compras',
    path: '/compras',
    url: '/compras',
    divider: false,
  },
  {
    id: 6,
    name: 'Gastos',
    path: '/gastos',
    url: '/gastos',
    divider: true,
  },
  {
    id: 7,
    name: 'Clientes',
    path: '/clientes',
    url: '/clientes',
    divider: false,
  },
  {
    id: 8,
    name: 'Ajustes',
    path: '/ajustes',
    url: '/ajustes',
    divider: false,
  },
];
