export const menuOptions = [
  {
    id: 0,
    name: 'Inicio',
    path: '/',
    url: '/',
    divider: true,
  },
  {
    id: 1,
    name: 'Ventas',
    path: '/ventas',
    url: '/ventas',
    divider: false,
  },
  {
    id: 2,
    name: 'Inventario',
    path: '/inventario',
    url: '/inventario',
    divider: false,
  },
  {
    id: 3,
    name: 'Productos',
    path: '/productos',
    url: '/productos',
    divider: true,
  },
  {
    id: 4,
    name: 'Compras',
    path: '/compras',
    url: '/compras',
    divider: false,
  },
  {
    id: 5,
    name: 'Gastos',
    path: '/gastos',
    url: '/gastos',
    divider: true,
  },
  {
    id: 6,
    name: 'Pedidos',
    path: '/pedidos',
    url: '/pedidos',
    divider: false,
  },
  {
    id: 7,
    name: 'Recibos',
    path: '/recibos',
    url: '/recibos',
    divider: true,
  },
  {
    id: 8,
    name: 'Clientes',
    path: '/clientes',
    url: '/clientes',
    divider: false,
  },
  {
    id: 9,
    name: 'Proveedores',
    path: '/proveedores',
    url: '/proveedores',
    divider: false,
  },
  {
    id: 10,
    name: 'Categorías',
    path: '/categorias',
    url: '/categorias',
    divider: true,
  },
];
